[package]
name = "envsub"
version = "0.0.3"
authors = ["Greg Dallavalle <greg.dallavalle@gmail.com>"]

[profile.release]
lto = true
panic = "abort"

[dependencies]
aho-corasick = "~0.7"

[dev-dependencies]
subprocess = "*"
